modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="fuelmod"
version="1.0"
displayName="Fuel Mod"
authors="sula008"
description='''Adds a fuel consumption system for Create trains and drills.'''

[[dependencies.fuelmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.fuelmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.fuelmod]]
modId="create"
mandatory=true
versionRange="[6.0,)"
ordering="AFTER"
side="BOTH"